app:
  contractAddress: '0xc66D32df5e3C7C692393E12e17CF66Eea9848e73'
  privateKey: ''
  rpc: 'https://rpc.bout.network'
  DataPath: './data/db/node.sqlite'
  heartbeatBatchSize: 100

logger:
  level: "debug"
  encoderType: "console"
  outputType: "all"
  maxAge: 30
  enableColor: true