app:
  contractAddress: '0xc550800B438809EfA0301f82dB45E5489025C010'
  privateKey: ''
  rpc: 'https://rpc.bout.network'
  DataPath: './data/db/node.sqlite'
  heartbeatBatchSize: 100

logger:
  level: "debug"
  encoderType: "console"
  outputType: "all"
  maxAge: 30
  enableColor: true