app:
  contractAddress: '0xd58a7bb11101940800c4d55e3dad2b83e51d3fd6'
  privateKey: ''
  rpc: 'https://rpc.bout.network'
  DataPath: './data/db/node.sqlite'
  heartbeatBatchSize: 100

logger:
  level: "debug"
  encoderType: "console"
  outputType: "all"
  maxAge: 30
  enableColor: true